### PR TITLE
Add support for persistent volumes

### PR DESCRIPTION
**Pull request by philipcristiano**
Persistent Volumes and Persistent Volume Claims.

### CODE REVIEW

**Comment by philipcristiano** [comment]
Applying labels to an existing PVC doesn't seem to work in kube, it's not an error but the labels are not present in the deployed configuration after application. I will likely remove the "apply" commit from this PR.

**Comment by philipcristiano** [comment]
@jmound thoughts?

**Comment by philipcristiano** [comment]
Ping @jmound

**Comment by jmound** [comment]
I haven’t responded earlier because i don’t know much about PVCs. Everythinghere looks good, but I'd like to see it in action. Is there a working example?

**Pull request merged**
