### PR TITLE
Example case for writing tests.

### PR DESCRIPTION
**Pull request by philipcristiano**
A spike to see if we could write tests for k8s-scripts in a reasonable manner without providing a cluster to test against. These should be able to run quickly in CI and allow us to refactor code without fear of breaking k8s-scripts functionality.

This works by creating a fake `kubectl` command that will record commands and allow the use of fixture data to replace stdout, stderr, and the exit code. 

A log is created of all fake commands to allow a comparison to expected output of commands run.

### CODE REVIEW

**Comment by philipcristiano** [comment]
@reactiveops/technical-team-members I'm interested in feedback for this idea/implementation path. It's getting more difficult to manually test k8s-scripts and would like an automated solution.

**Comment by opennomad** [comment]
I personally favor the testing against real cluster, since there are a lot of variables involved with the underlying kube environment. I'm also impatient, and so this seems quite attractive. @philipcristiano do you see maintenance of the fixture data as hard/tedious/burdensome? Perhaps a workflow would be to test on live cluster occasionally to ensure fixture data is still valid?

**Comment by philipcristiano** [comment]
This could also help when making PRs for people not in our org. Would be nice to have some kind of test without actually running code in our AWS account. 

The fixtures could be a problem to maintain depending on how strict we make the code for them. If we have sane defaults of exit code 0 it probably isn't too much. 

A problem I've noticed already, the commands hashed to use for fixtures are absolute paths in k8s-scripts, which means a little more work to strip them out before hashing, but is doable. 

Like any kind of unit testing there will be a need to validate that operations still function when integrated. When I've added features I integrate this into a client to make sure it's not broken, but only for the new feature, not the rest of the code. Not sure where the balance is for testing shell scripts like this though.

**Comment by philipcristiano** [comment]
This has the unfortunate situation of not really working on different systems. For the time being I'm unlikely to work on this and will close it out.

**Pull request closed without merging**
