### PR TITLE
secrets-from-s3: Generate secrets from blob storage

### PR DESCRIPTION
**Pull request by philipcristiano**
Generate k8s secrets from an s3 bucket that can be deployed with 
k8s-deploy.

### CODE REVIEW

**Comment by philipcristiano** [comment]
@reactiveops/technical-team-members 

Deploy with a client in CircleCI and working.

**Comment by rosskukulinski** [comment]
\0/ Awesome @philipcristiano

**Comment by emalloy** [comment]
Works great for me!

Would like to see this merged and released

**Comment by philipcristiano** [comment]
In the absence of comments about the code I will update docs next free day I get and merge/release.

**Comment by philipcristiano** [comment]
Updated docs and will merge/tag this.

**Pull request merged**
