### PR TITLE
Improved deployment

### PR DESCRIPTION
**Pull request by arohner**
This does quite a lot, sorry. 
- rename deploy-service to rolling-update. Upstream already has k8s-deploy, and the existing code had races, because it `kubectl apply'd` multiple times, causing a race.
- use k8s-read-config in rolling-update, verify-deployment
- no longer set kube context in scripts. User is responsible for setting context before calling
- no longer specify kubectl by absolute path. User is responsible for making sure kubectl is on the path
- allow specifying the version of kubectl to install, via env var KUBE_VERSION
- use bash strict mode as much as possible, `set -e` and `-o pipefail`. Can't `set -u` because k8s-config allows for empty bash arrays, and `set -u` interacts very poorly with empty arrays. 
- adds `yq` a slimmed-down version of https://github.com/wildducktheories/y2j, which doesn't use docker. Use `yq` in several places that previously used `sed` on yaml files.

### CODE REVIEW

**Comment by philipcristiano** [comment]
@arohner is this still something you would like to get merged?

**Comment by arohner** [comment]
Yes, though now I'm concerned about the cost of merging it. When I wrote
it, I believe only Koombea was using k8s in production. Now this will
probably introduce breaking changes, so someone with more visibility into
the other projects than me will need to consider it.

**Comment by philipcristiano** [comment]
Breaking changes would be fine if we tag appropriately. This will need to be rebased though.

**Comment by philipcristiano** [comment]
This has conflicts and has aged a bit from what is going on in k8s-scripts now. If more work happens on this it could be merged but will close the PR for now.

**Pull request closed without merging**
